version: '3.8'

services:
  nestjs-app:
    build: .
    container_name: nestjs-container
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
      - ./database.sqlite:/app/database.sqlite # ✅ 로컬 데이터베이스 유지
    env_file:
      - .env # ✅ .env 파일을 자동으로 로드하여 환경변수 적용

